### PR TITLE
Add systemd service (clean fork)

### PR DESCRIPTION
**Pull request by drakeerv**

### CODE REVIEW

**Comment by lorenzogood** [comment]
Thanks

**Comment by lorenzogood** [comment]
@drakeerv In this case we don't actually want the install script to install the service automatically, or at all. This is because people that need to do development don't want any incidents, and systems exist where this could crash the script and cause issues. Can you rebase the branch and edit the commit?

**Comment by drakeerv** [comment]
Would it be possible to make a separate install.sh to make it easier to install on a linux system and a setup.sh to setup the dev environment? Personally I think that it would make it a lot easier to install and run on SBCs. Otherwise, I will take out the auto service installer and keep it on 4533's branch.

**Comment by lorenzogood** [comment]
No reason to do so, especially because the service file is an optional functionality, just take out the auto service installer. Thanks.

**Comment by drakeerv** [comment]
@foehammer127 Done

**Comment by lorenzogood** [comment]
Great, thanks!

**Comment by lorenzogood** [comment]
I can make the wiki entry.

**Comment by drakeerv** [comment]
Alright, %p is the base path, and %s is the main script.

Ex:
%p = /home/drakeerv/TagTracker
%s = src/main.py

**Pull request merged**
